CXX ?= clang++
SDL2_CFLAGS := $(shell pkg-config --cflags sdl2 2>/dev/null)
SDL2_LIBS := $(shell pkg-config --libs sdl2 2>/dev/null)
# SDL2_CFLAGS folded in globally: pattern-rule specificity in this Makefile
# doesn't reliably beat the generic $(BUILD)/%.o rule, and several non-SDL
# files (engine.h) transitively need SDL2's headers anyway.
CXXFLAGS := -std=c++20 -O2 -Wall -Wextra -Iinclude -Ithird_party -Wno-unused-parameter -pthread $(SDL2_CFLAGS)
AUDIO_CXXFLAGS := $(CXXFLAGS)

BUILD := build

DSP_SRCS := $(wildcard src/dsp/*.cpp)
DSP_OBJS := $(patsubst src/%.cpp,$(BUILD)/%.o,$(DSP_SRCS))

GFX_SRCS := $(wildcard src/gfx/*.cpp)
GFX_OBJS := $(patsubst src/%.cpp,$(BUILD)/%.o,$(GFX_SRCS))

APP_SRCS := $(wildcard src/app/*.cpp)
APP_OBJS := $(patsubst src/%.cpp,$(BUILD)/%.o,$(APP_SRCS))

AUDIO_SRCS := $(wildcard src/audio/*.cpp)
AUDIO_OBJS := $(patsubst src/%.cpp,$(BUILD)/%.o,$(AUDIO_SRCS))

UNAME_S := $(shell uname -s)
ARCH := $(shell uname -m)

ifeq ($(UNAME_S),Darwin)
APP_OBJS += $(BUILD)/app/menu_bar_icon.o $(BUILD)/app/media_remote.o $(BUILD)/app/main_menu.o
FRAMEWORKS := -framework Cocoa -framework MediaPlayer -framework CoreFoundation
else
FRAMEWORKS :=
endif

# BASE_VERSION is hand-bumped for real milestones; the trailing component is
# the git commit count, so the same commit always produces the same version
# number no matter who builds it - no local counter file to keep in sync.
# Platform-agnostic so both the macOS .dmg and the Linux tarball below carry
# a correct, matching version.
BASE_VERSION := 1.2
APP_VERSION := $(BASE_VERSION).$(shell git rev-list --count HEAD 2>/dev/null || echo 0)

# include/app/version.h is generated, not hand-edited - regenerated on every
# build (cheap: just a string compare) via the always-out-of-date FORCE
# target, but only actually rewritten (and thus only bumps its mtime, which
# is what triggers main.o's recompile below) when APP_VERSION really changed.
.PHONY: FORCE
FORCE:

include/app/version.h: FORCE
	@tmp=$$(mktemp); \
	printf '#pragma once\n\n// Auto-generated by the Makefile from BASE_VERSION + the git commit\n// count - do not hand-edit. Bump BASE_VERSION in the Makefile for a real\n// milestone version change.\n\nnamespace xmad::app {\n\nconstexpr const char* kVersion = "%s";\n\n} // namespace xmad::app\n' "$(APP_VERSION)" > "$$tmp"; \
	cmp -s "$$tmp" "$@" 2>/dev/null && rm -f "$$tmp" || mv "$$tmp" "$@"

.PHONY: all test run clean

ifeq ($(UNAME_S),Darwin)
all: test app
else
all: test $(BUILD)/xmad
endif

$(BUILD)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(UNAME_S),Darwin)
$(BUILD)/app/%.o: src/app/%.mm
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -fobjc-arc -c $< -o $@
endif

$(BUILD)/main.o: src/main.cpp include/app/version.h
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(SDL2_CFLAGS) -c $< -o $@

$(BUILD)/audio/%.o: src/audio/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(AUDIO_CXXFLAGS) $(SDL2_CFLAGS) -c $< -o $@

# --- fft smoke test ----------------------------------------------------------
$(BUILD)/fft_smoke_test: tests/fft_smoke_test.cpp $(DSP_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(CXXFLAGS) $^ -o $@

# --- bitmap font render test --------------------------------------------------
$(BUILD)/font_render_test: tests/font_render_test.cpp $(GFX_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(CXXFLAGS) $^ -o $@

# --- decoder test --------------------------------------------------------------
$(BUILD)/decoder_test: tests/decoder_test.cpp $(AUDIO_OBJS) $(DSP_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(AUDIO_CXXFLAGS) $(SDL2_CFLAGS) $^ -o $@ $(SDL2_LIBS)

# --- engine smoke test (real-time playback through the real audio device) -----
$(BUILD)/engine_smoke_test: tests/engine_smoke_test.cpp $(AUDIO_OBJS) $(DSP_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(AUDIO_CXXFLAGS) $^ -o $@ $(SDL2_LIBS)

# --- equalizer test --------------------------------------------------------------
$(BUILD)/eq_test: tests/eq_test.cpp $(AUDIO_OBJS) $(DSP_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(AUDIO_CXXFLAGS) $^ -o $@ $(SDL2_LIBS)

# --- window snap (magnetic docking) test - no SDL dependency ------------------
$(BUILD)/window_snap_test: tests/window_snap_test.cpp $(BUILD)/app/window_snap.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- file dialog (Eject button) test - pure parsing only, no SDL --------------
$(BUILD)/file_dialog_test: tests/file_dialog_test.cpp $(BUILD)/app/file_dialog.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- session persistence (save-settings-on-exit) test - pure parsing only, no SDL --
$(BUILD)/session_test: tests/session_test.cpp $(BUILD)/app/session.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- XSound stereo widener test - pure math, no SDL -----------------------
$(BUILD)/stereo_widen_test: tests/stereo_widen_test.cpp $(BUILD)/audio/stereo_widen.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- saturation waveshaper test - harmonic content via FFT, no SDL dep ------
$(BUILD)/saturation_test: tests/saturation_test.cpp $(BUILD)/audio/saturation.o $(DSP_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(CXXFLAGS) $^ -o $@

# --- compressor gain-reduction test - pure math, no SDL ---------------------
$(BUILD)/compressor_test: tests/compressor_test.cpp $(BUILD)/audio/compressor.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- chorus modulated-delay test - pure math, no SDL -------------------------
$(BUILD)/chorus_test: tests/chorus_test.cpp $(BUILD)/audio/chorus.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- reverb comb/allpass network test - pure math, no SDL --------------------
$(BUILD)/reverb_test: tests/reverb_test.cpp $(BUILD)/audio/reverb.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- channel-level LED gradient test - pure color math, no SDL -------------
$(BUILD)/level_meter_test: tests/level_meter_test.cpp $(BUILD)/gfx/level_meter.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- ID3 title parsing test - pure parsing only, no SDL ---------------------
# (links dr_impl.o for dr_flac's implementation, which tags.o's FLAC path
# calls into - only the pure ID3 functions are actually exercised by this
# test binary, but the symbols still need to resolve.)
$(BUILD)/tags_test: tests/tags_test.cpp $(BUILD)/audio/tags.o $(BUILD)/audio/dr_impl.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude -Ithird_party $^ -o $@

# --- playlist M3U load/save (relative-path resolution) test - no SDL ---------
$(BUILD)/playlist_test: tests/playlist_test.cpp $(BUILD)/app/playlist.o
	@mkdir -p $(BUILD)
	$(CXX) -std=c++20 -O2 -Wall -Wextra -Iinclude $^ -o $@

# --- the app -------------------------------------------------------------------
$(BUILD)/xmad: $(BUILD)/main.o $(GFX_OBJS) $(APP_OBJS) $(DSP_OBJS) $(AUDIO_OBJS)
	@mkdir -p $(BUILD)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(SDL2_LIBS) $(FRAMEWORKS)

# --- macOS .app bundle, so a Dock/Finder icon (the real extracted SKULL.ico
# resource) actually applies - a bare Unix executable gets the generic
# terminal icon, since Dock icons come from CFBundleIconFile in an app
# bundle's Info.plist, not from anything SDL can set at runtime. ------------
ifeq ($(UNAME_S),Darwin)
APP_BUNDLE := $(BUILD)/xmad.app

.PHONY: app
app: $(APP_BUNDLE)

$(APP_BUNDLE): $(BUILD)/xmad assets/icon/Info.plist assets/icon/AppIcon.icns $(wildcard assets/skin/*)
	@mkdir -p "$(APP_BUNDLE)/Contents/MacOS" "$(APP_BUNDLE)/Contents/Resources" "$(APP_BUNDLE)/Contents/Frameworks"
	cp $(BUILD)/xmad "$(APP_BUNDLE)/Contents/MacOS/xmad"
	sdl2_dylib=$$(otool -L "$(APP_BUNDLE)/Contents/MacOS/xmad" | awk '/libSDL2-2\.0\.0\.dylib/ {print $$1; exit}') && \
	cp -L "$$sdl2_dylib" "$(APP_BUNDLE)/Contents/Frameworks/libSDL2-2.0.0.dylib" && \
	install_name_tool -id "@executable_path/../Frameworks/libSDL2-2.0.0.dylib" "$(APP_BUNDLE)/Contents/Frameworks/libSDL2-2.0.0.dylib" && \
	install_name_tool -change "$$sdl2_dylib" "@executable_path/../Frameworks/libSDL2-2.0.0.dylib" "$(APP_BUNDLE)/Contents/MacOS/xmad"
	codesign --force --sign - "$(APP_BUNDLE)/Contents/Frameworks/libSDL2-2.0.0.dylib"
	cp assets/icon/AppIcon.icns "$(APP_BUNDLE)/Contents/Resources/AppIcon.icns"
	sed 's/@VERSION@/$(APP_VERSION)/g' assets/icon/Info.plist > "$(APP_BUNDLE)/Contents/Info.plist"
	rm -rf "$(APP_BUNDLE)/Contents/Resources/skin"
	cp -R assets/skin "$(APP_BUNDLE)/Contents/Resources/skin"
	touch "$(APP_BUNDLE)"

# --- distributable .dmg: the .app plus a symlink to /Applications, the
# standard drag-to-install layout - built from a throwaway staging dir
# (not the bundle's own location) so the symlink never ends up inside the
# .app itself. Requires the full test suite to pass first, so nothing
# broken ever ships. The staged copy is ad-hoc codesigned (no Developer ID,
# free) so Gatekeeper's quarantine check reports "unidentified developer"
# instead of the misleading "app is damaged" it shows for wholly unsigned
# bundles; it still requires right-click > Open on first launch. -----------
DMG_NAME := X.MaD-Player-Revival-$(APP_VERSION).dmg
DMG_STAGING := $(BUILD)/dmg_staging

.PHONY: dmg
dmg: test app
	rm -rf "$(DMG_STAGING)" "$(BUILD)/$(DMG_NAME)"
	mkdir -p "$(DMG_STAGING)"
	cp -R "$(APP_BUNDLE)" "$(DMG_STAGING)/"
	codesign --force --sign - "$(DMG_STAGING)/xmad.app"
	ln -s /Applications "$(DMG_STAGING)/Applications"
	hdiutil create -volname "X.MaD Player Revival" -srcfolder "$(DMG_STAGING)" -ov -format UDZO "$(BUILD)/$(DMG_NAME)"
	rm -rf "$(DMG_STAGING)"
	@echo "Wrote $(BUILD)/$(DMG_NAME)"
else
# --- distributable Linux tarball: the binary plus the assets it needs next
# to it - main.cpp's ResolveDefaultAssetDir() already looks for a "skin"
# dir sitting alongside the executable, so this layout runs standalone
# after a plain extract, no install step required. Staged under a
# throwaway dir (not build/ itself) so the tarball's top-level entry is a
# clean "xmad-<version>/" folder. Requires the full test suite to pass
# first, so nothing broken ever ships. -------------------------------------
TARBALL_NAME := X.MaD-Player-Revival-$(APP_VERSION)-linux-$(ARCH).tar.gz
TARBALL_STAGING := $(BUILD)/tarball_staging
TARBALL_DIR := xmad-$(APP_VERSION)

.PHONY: tarball
tarball: test $(BUILD)/xmad
	rm -rf "$(TARBALL_STAGING)" "$(BUILD)/$(TARBALL_NAME)"
	mkdir -p "$(TARBALL_STAGING)/$(TARBALL_DIR)"
	cp $(BUILD)/xmad "$(TARBALL_STAGING)/$(TARBALL_DIR)/xmad"
	cp -R assets/skin "$(TARBALL_STAGING)/$(TARBALL_DIR)/skin"
	tar -C "$(TARBALL_STAGING)" -czf "$(BUILD)/$(TARBALL_NAME)" "$(TARBALL_DIR)"
	rm -rf "$(TARBALL_STAGING)"
	@echo "Wrote $(BUILD)/$(TARBALL_NAME)"
endif

test: $(BUILD)/fft_smoke_test $(BUILD)/font_render_test $(BUILD)/decoder_test $(BUILD)/engine_smoke_test $(BUILD)/eq_test $(BUILD)/window_snap_test $(BUILD)/file_dialog_test $(BUILD)/session_test $(BUILD)/stereo_widen_test $(BUILD)/tags_test $(BUILD)/level_meter_test $(BUILD)/playlist_test $(BUILD)/saturation_test $(BUILD)/compressor_test $(BUILD)/chorus_test $(BUILD)/reverb_test
	./$(BUILD)/fft_smoke_test
	./$(BUILD)/font_render_test "../xmplayer/Source/Img_new/DISPLAY.bmp" $(BUILD)/font_render.raw
	./$(BUILD)/decoder_test
	./$(BUILD)/engine_smoke_test tests/fixtures/tone.mp3
	./$(BUILD)/eq_test
	./$(BUILD)/window_snap_test
	./$(BUILD)/file_dialog_test
	./$(BUILD)/session_test
	./$(BUILD)/stereo_widen_test
	./$(BUILD)/tags_test
	./$(BUILD)/level_meter_test
	./$(BUILD)/playlist_test
	./$(BUILD)/saturation_test
	./$(BUILD)/compressor_test
	./$(BUILD)/chorus_test
	./$(BUILD)/reverb_test

ifeq ($(UNAME_S),Darwin)
# Launched through the .app bundle via `open` (not the raw binary) so
# the real skull-and-crossbones Dock icon actually shows - confirmed
# this session that `open`-launching the bundle is what makes macOS
# read CFBundleIconFile; running the raw binary never does, bundle or not.
run: app
	open "$(APP_BUNDLE)" --args assets/skin tests/fixtures/track_a.mp3 tests/fixtures/track_b.mp3 tests/fixtures/track_c.flac
else
run: $(BUILD)/xmad
	./$(BUILD)/xmad assets/skin tests/fixtures/track_a.mp3 tests/fixtures/track_b.mp3 tests/fixtures/track_c.flac
endif

clean:
	rm -rf $(BUILD)
