#pragma once

// Auto-generated by the Makefile from BASE_VERSION + the git commit
// count - do not hand-edit. Bump BASE_VERSION in the Makefile for a real
// milestone version change.

namespace xmad::app {

constexpr const char* kVersion = "1.0.34";

} // namespace xmad::app
